services:
  pkgui-server:
    container_name: pkgui-server
    hostname: pkguiserver
    build:
      context: ./pkgui-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    networks:
      - pkgui-server-network
    volumes:
      - ./pkgui-server.env:/etc/pkgui-server/pkgui-server.env
  pkgui-nginx:
    container_name: pkgui-nginx
    hostname: pkguinginx
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./pkgui-frontend/dist/:/var/www/dist/
      - ./pkgui-frontend/assets/:/var/www/assets/
    ports:
      - "${PORT}:80"
    networks:
      - pkgui-server-network

networks:
  pkgui-server-network:
    driver: bridge
