services:
  api:
    container_name: api
    hostname: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app-network
  frontend:
    container_name: frontend
    hostname: frontend
    build:
      context: ./frontend/serve
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app-network
  nginx: 
    container_name: nginx
    hostname: nginx
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
