services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:8000"
  frontend:
    container_name: frontend
    build:
      context: ./frontend/serve
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
  nginx: 
    container_name: nginx
    image: nginx:1.21
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.k-configmap
    ports:
      - "80:80"
